services:
  user-db:
    image: postgres:16.1
    container_name: ewm-user-db
    environment:
      POSTGRES_DB: ewm_user
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - user-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  stats-db:
    image: postgres:16.1
    container_name: ewm-stats-db
    environment:
      POSTGRES_DB: stats
      POSTGRES_USER: stats
      POSTGRES_PASSWORD: stats
    ports:
      - "5433:5432"
    volumes:
      - stats-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stats"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  user-db-data:
    driver: local
  stats-db-data:
    driver: local