server:
  port: 0

spring:
  application:
    name: collector
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: ${SCHEMA_REGISTRY_URL:http://localhost:8085}
  config:
    import: optional:configserver:http://localhost:8888

grpc:
  server:
    port: 59091
    enable: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${random.value}

logging:
  level:
    ru.practicum: DEBUG
    org.springframework.kafka: INFO